export enum Color {
  cascada_colors_light_green = '#ECF4EF',
  cascada_colors_green_accent = '#008943',
  cascada_colors_cascada_secondary = '#5B7A79',
  cascada_colors_green_accent_dark = '#017840',
  cascada_colors_cascada_primary = '#063532',
  cascada_colors_background = '#F8FBF9',
  ui_white = '#FFFFFF',
  ui_stroke = '#D6DFDA',
  ui_stroke_2 = '#C0CBC5',
  ui_alert_dark = '#A32938',
  ui_alert_default = '#DC3045',
  ui_alert_light = '#BC4A63',
  ui_orange_light = '#F7CA90',
  ui_orange_dark = '#A56722',
  ui_teal_dark = '#03838E',
  ui_teal_light = '#A2EFE6',
}